# Generated by Django 3.0.7 on 2020-07-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Температура')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cityes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherManager.City')),
            ],
        ),
    ]
