# Generated by Django 3.0.7 on 2020-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'Температура', 'verbose_name_plural': 'Температура'},
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Температура'),
        ),
    ]
