# Generated by Django 3.0.7 on 2020-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherManager', '0007_auto_20200702_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.CharField(max_length=2, verbose_name='Температура'),
        ),
    ]
