# Generated by Django 3.0.8 on 2020-07-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherManager', '0008_auto_20200703_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='cityes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='City', to='weatherManager.City'),
        ),
    ]
